# module for configuring the simulator
# configuration parameters are loaded and used both when using the simulator via the CLI and via the interface
# all parameters are required, defaults are in comments

inter_arrival_mean: 10.0           # default: 10.0
deterministic_arrival: False        # default: True
flow_dr_mean: 1.0                  # default: 1.0
flow_dr_stdev: 0.0                 # default: 0.0
flow_size_shape: 0.001             # default: 0.001 (for deterministic!)
deterministic_size: True           # default: True

run_duration: 100                  # default: 100

# Timeout to remove inactive VNFs from services
vnf_timeout: 100                   # default: 200

# TTL list: Randomly select a TTL from the following list for each flow
ttl_choices: [100]

controller_class: FlowController
decision_maker_class: ExternalDecisionMaker

# Optional: Trace file trace relative to the CWD.
# Until values start in the trace file, the defaults from this file are used
# trace_path: params/traces/default_trace.csv

# Optional: Write Scheduling results
# write_schedule: True

# # States (two state markov arrival)
# # Optional param: states: True | False 
# use_states: False
# # Set the init state for nodes
# init_state: state_1
# # Optional: Apply random states as init. Oerrides the state defined in init_state. 
# rand_init_state: True 
# states:
#   state_1:
#     inter_arr_mean: 10.0
#     switch_p: 0.8
#   state_2:
#     inter_arr_mean: 2.0
#     switch_p: 0.3