# module for configuring the simulator
# configuration parameters are loaded and used both when using the simulator via the CLI and via the interface
# all parameters are required, defaults are in comments

inter_arrival_mean: 12.0 # default: 10.0
deterministic_arrival: False
flow_dr_mean: 1.0 # default: 1.0
flow_dr_stdev: 0.0 # default: 0.0
flow_size_shape: 0.001 # default: 0.001
deterministic_size: True

run_duration: 100 # default: 100

# Timeout to remove inactive VNFs from services
vnf_timeout: 100                   # default: 200

# TTL list: Randomly select a TTL from the following list for each flow
ttl_choices: [100]

controller_class: FlowController
decision_maker_class: ExternalDecisionMaker

# Optional: Write Scheduling results, uncomment to create schedule file
# write_schedule: True

# Optional: Trace file trace relative to the CWD.
# Until values start in the trace file, the defaults from this file are used
# trace_path: res/traces/scenario09.csv

# States (two state markov arrival)
# Optional param: states: True | False
use_states: True
init_state: state_1

states:
  state_1:
    inter_arr_mean: 12.0
    switch_p: 0.05
  state_2:
    inter_arr_mean: 8.0
    switch_p: 0.05
